spring:
  datasource:
    #数据库类型
    type: com.zaxxer.hikari.HikariDataSource
    #连接数据库的工具
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库的地址
    url: jdbc:mysql://localhost:3306/mybatisplus?characterEncoding=utf-8&userSSL=false
    username: root
    password: root

#使用MybatisPlus，用的是包里面写好的方法，SQL语句没有
#办法展示出来，使用下面的代码可以展示出SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  #全局配置，实体类中到数据库中，全部都加上这个前缀
  global-config:
    db-config:
      table-prefix: t_
  #使用枚举，扫描对应的包，把包里面的内容属性填充到数据库中
  type-enums-package: com.sias.plus.enums